changelog:
  categories:
    - title: "Breaking Changes"
      labels: ["breaking"]
    - title: "Features"
      labels: ["feature"]
    - title: "Bug Fixes"
      labels: ["fix"]
    - title: "Documentation"
      labels: ["documentation"]
    - title: "Maintenance"
      labels: ["chore"]
    - title: "Other"
      labels: ["*"]
